name: Lighthouse CI Test
on: 
  pull_request :
    branches: [master]
jobs:
  test-pull-request : 
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v1
        with:
          node-version: 12
      - run : npm ci
      - run : npm install -g @lhci/cli@0.4.x
      - run : npm build
      - run : lhci autorun --upload.target=temporary-public-storage
      
