# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lighthouse Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install , build
    - run: |
        yarn
        npm run build
    - name : run Lighthouse CI
    - run: |
        npm install -g @lhci/cli@0.3.x
        lhci autorun --upload.target=temporory-public-storage || echo "LHCI failed"
      
